server:
  port: 63003
spring:
  application:
    name: data-service
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
  client:
    register-with-eureka: true #是否注册
    fetch-registry: true #是否拉取
    service-url:
      defaultZone: http://127.0.0.1:65201/eureka/