logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
server:
  port: 65301

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:65201/eureka/