server:
  port: 65201
  servlet:
    context-path: /
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: false
    fetchRegistry: false
