eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:65201/eureka/
    fetch-registry: false
    register-with-eureka: false

server:
  servlet:
    context-path: /preApp
  port: 63001
spring:
  application:
    name: preApp